// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG9b9wE8zyHsK8vp3G3Qnw2xU5-W0NKYM',
    appId: '1:331455913145:web:b1ef01812e6be9b5884f68',
    messagingSenderId: '331455913145',
    projectId: 'exp7-5f06b',
    authDomain: 'exp7-5f06b.firebaseapp.com',
    storageBucket: 'exp7-5f06b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8XPMMppyHFFI7s1Vi56_CV_h0RMAKzs',
    appId: '1:331455913145:android:85dab58129d4ac4e884f68',
    messagingSenderId: '331455913145',
    projectId: 'exp7-5f06b',
    storageBucket: 'exp7-5f06b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjS-NG1z23NbgrlsxyodQS__wRxbva0h8',
    appId: '1:331455913145:ios:591f2663497b08e9884f68',
    messagingSenderId: '331455913145',
    projectId: 'exp7-5f06b',
    storageBucket: 'exp7-5f06b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjS-NG1z23NbgrlsxyodQS__wRxbva0h8',
    appId: '1:331455913145:ios:591f2663497b08e9884f68',
    messagingSenderId: '331455913145',
    projectId: 'exp7-5f06b',
    storageBucket: 'exp7-5f06b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG9b9wE8zyHsK8vp3G3Qnw2xU5-W0NKYM',
    appId: '1:331455913145:web:17003a192a56c3be884f68',
    messagingSenderId: '331455913145',
    projectId: 'exp7-5f06b',
    authDomain: 'exp7-5f06b.firebaseapp.com',
    storageBucket: 'exp7-5f06b.firebasestorage.app',
  );
}
